### ISSUE TITLE
constrains rdflib to 4.2.2?

### ISSUE THREAD

**Issue by teledyn** [scrapinghub/extruct#136] opened 2020-05-07 19:10 UTC
extruct appears to be the only item in my scrapy installation that is still constraining to rdf 4.2.2 -- are there plans for an update?

**Comment by Gallaecio** [comment] 2020-05-07 19:15
See #135

**Comment by lopuhin** [comment] 2020-05-08 07:16
We want to lift this restriction but no concrete timeline yet, PRs are always welcome. I'll close this as a duplicate of #135 as @Gallaecio noted.

**Closed by lopuhin** 2020-05-08 07:16 UTC
