### ISSUE TITLE
ImportError: cannot import name '_ElementStringResult' from 'lxml.etree'

### ISSUE THREAD

**Issue by tonal** [scrapinghub/extruct#216] opened 2024-04-01 07:32 UTC
In latest lxml (5.1.1, 5.2.0) error for import extruct
```
$ pip install -U extruct lxml
$ python -c 'import extruct'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.pyenv/versions/3.11.7/envs/epool-remains_prefect/lib/python3.11/site-packages/extruct/__init__.py", line 1, in <module>
    from ._extruct import SYNTAXES, extract
  File "/home/user/.pyenv/versions/3.11.7/envs/epool-remains_prefect/lib/python3.11/site-packages/extruct/_extruct.py", line 9, in <module>
    from extruct.dublincore import DublinCoreExtractor
  File "/home/user/.pyenv/versions/3.11.7/envs/epool-remains_prefect/lib/python3.11/site-packages/extruct/dublincore.py", line 6, in <module>
    from extruct.utils import parse_html
  File "/home/user/.pyenv/versions/3.11.7/envs/epool-remains_prefect/lib/python3.11/site-packages/extruct/utils.py", line 5, in <module>
    from extruct.xmldom import XmlDomHTMLParser
  File "/home/user/.pyenv/versions/3.11.7/envs/epool-remains_prefect/lib/python3.11/site-packages/extruct/xmldom.py", line 9, in <module>
    from lxml.etree import (
ImportError: cannot import name '_ElementStringResult' from 'lxml.etree' (/home/user/.pyenv/versions/3.11.7/envs/epool-remains_prefect/lib/python3.11/site-packages/lxml/etree.cpython-311-x86_64-linux-gnu.so)
```

**Comment by wRAR** [comment] 2024-04-01 07:48
Duplicate of #215

**Closed by wRAR** 2024-04-01 07:48 UTC
